# ex: set ro:
# DO NOT EDIT THIS FILE
# Generated by Parrot::Configure::Compiler from languages/punie/config/makefiles/root.in

# Copyright (C) 2005-2009, Parrot Foundation.
# $Id: root.in 36833 2009-02-17 20:09:26Z allison $

# Setup some commands
LN_S     = /bin/ln -s
PERL     = /usr/bin/perl
RM_F     = $(PERL) -MExtUtils::Command -e rm_f
PARROT   = ../../parrot
BUILD_DIR     = /home/allison/projects/svn/parrot
RECONFIGURE   = $(PERL) /home/allison/projects/svn/parrot/tools/dev/reconfigure.pl
PGE_DIR       = ../../compilers/pge
NQP_DIR       = ../../compilers/nqp
CP       = $(PERL) -MExtUtils::Command -e cp

PARROT_LIBRARY = ../../runtime/parrot/library
PGE_LIBRARY   = ../../runtime/parrot/library/PGE

# the default target
all: punie.pbc

SOURCES = punie.pir \
  src/parser/grammar.pg \
  src/parser/actions.pm \
  src/builtins/builtins.pir \

# the default target
punie.pbc: $(PARROT) $(NQP_DIR)/nqp.pbc $(PGE_LIBRARY)/Perl6Grammar.pir $(SOURCES)
	$(PARROT) $(PGE_LIBRARY)/Perl6Grammar.pir --output=src/gen_punie.pir src/parser/grammar.pg
	$(PARROT) $(NQP_DIR)/nqp.pbc --target=pir --output=src/gen_punie-actions.pir src/parser/actions.pm
	$(PARROT) -o punie.pbc punie.pir

# This is a listing of all targets, that are meant to be called by users
help:
	@echo ""
	@echo "Following targets are available for the user:"
	@echo ""
	@echo "  all:               punie.pbc"
	@echo "                     This is the default."
	@echo "Testing:"
	@echo "  test:              Run the test suite."
	@echo "  testclean:         Clean up test results."
	@echo ""
	@echo "Cleaning:"
	@echo "  clean:             Basic cleaning up."
	@echo "  realclean:         Removes also files generated by 'Configure.pl'"
	@echo "  distclean:         Removes also anything built, in theory"
	@echo ""
	@echo "Misc:"
	@echo "  help:              Print this help message."
	@echo ""

test: all
	$(PERL) -Ilib -I../../lib t/harness

# regenerate the Makefile
Makefile: config/makefiles/root.in
	cd $(BUILD_DIR) && $(RECONFIGURE) --step=gen::languages --languages=punie

testclean:
	$(RM_F) "t/*.p1" "t/*.out" "t/*.pir"

CLEANUPS = \
  punie.pbc \
  src/gen_punie.pir \
  src/gen_punie-actions.pir \

clean: testclean
	$(RM_F) $(CLEANUPS)

realclean: clean
	$(RM_F) Makefile

distclean: realclean

# Local variables:
#   mode: makefile
# End:
# vim: ft=make:
